import { createClient } from '@supabase/supabase-js';
import type { Book } from '../types/book';
import { STORAGE_KEYS } from './config';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

export const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey && supabaseUrl !== 'https://your-project.supabase.co');

export const supabase = isSupabaseConfigured
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null;

// Curated 25 Publications with rich metadata, covers, descriptions, and reliable streaming PDF URLs
export const INITIAL_BOOKS: Book[] = [
  {
    id: '1',
    book_number: 1,
    title: 'Global Horizons: Annual Innovation Report 2026',
    slug: 'annual-report-2026',
    description: 'A comprehensive study on emerging technology trends, AI acceleration, sustainable infrastructure, and global market dynamics.',
    cover_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Technology & Business',
    author: 'Horizon Research Institute',
    publication_date: '2026-01-15',
    page_count: 14,
    file_size: 1048576,
    is_published: true,
    display_order: 1,
  },
  {
    id: '2',
    book_number: 2,
    title: 'Architectural Digest: Sustainable Mega-Structures',
    slug: 'architectural-digest-sustainable-structures',
    description: 'Exploring biophilic skyscrapers, timber engineering, and zero-carbon urban habitats across five continents.',
    cover_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Architecture & Design',
    author: 'Elena Rostova & Studio Arch',
    publication_date: '2026-02-10',
    page_count: 14,
    file_size: 2097152,
    is_published: true,
    display_order: 2,
  },
  {
    id: '3',
    book_number: 3,
    title: 'Deep Space Odyssey: James Webb Frontiers',
    slug: 'deep-space-odyssey',
    description: 'High-resolution photometric data, cosmic dawn surveys, and spectroscopy results from deep galactic clusters.',
    cover_url: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Science & Astrophysics',
    author: 'Astrophysical Sciences Council',
    publication_date: '2026-03-01',
    page_count: 14,
    file_size: 4194304,
    is_published: true,
    display_order: 3,
  },
  {
    id: '4',
    book_number: 4,
    title: 'The Art of Typography & Editorial Layout',
    slug: 'art-of-typography',
    description: 'A visual celebration of modernist grids, Swiss design principles, serif evolution, and digital editorial mastery.',
    cover_url: 'https://images.unsplash.com/photo-1507842229451-79b1be046a22?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Visual Arts',
    author: 'Marcus Vance',
    publication_date: '2025-11-20',
    page_count: 14,
    file_size: 3145728,
    is_published: true,
    display_order: 4,
  },
  {
    id: '5',
    book_number: 5,
    title: 'Quantum Computing: From Theory to Scalable Qubits',
    slug: 'quantum-computing-principles',
    description: 'Technical analysis on topological qubits, quantum error mitigation, and cryptographic implications.',
    cover_url: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Technology & Business',
    author: 'Dr. Aris Thorne',
    publication_date: '2025-12-05',
    page_count: 14,
    file_size: 5242880,
    is_published: true,
    display_order: 5,
  },
  {
    id: '6',
    book_number: 6,
    title: 'Oceanic Conservation & Marine Biodiversity',
    slug: 'oceanic-conservation-review',
    description: 'Global coral reef restoration surveys, benthic ecosystem health indices, and marine protected zone metrics.',
    cover_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Environment & Ecology',
    author: 'Pacific Marine Institute',
    publication_date: '2025-10-18',
    page_count: 14,
    file_size: 4718592,
    is_published: true,
    display_order: 6,
  },
  {
    id: '7',
    book_number: 7,
    title: 'Monograph: Minimalism in Contemporary Japanese Design',
    slug: 'minimalism-japanese-design',
    description: 'An intimate examination of Ma (negative space), joinery traditions, and wabi-sabi philosophy in modern industrial items.',
    cover_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Visual Arts',
    author: 'Kenji Sato',
    publication_date: '2025-09-14',
    page_count: 14,
    file_size: 2621440,
    is_published: true,
    display_order: 7,
  },
  {
    id: '8',
    book_number: 8,
    title: 'Renewable Energy Grid Orchestration 2030',
    slug: 'renewable-energy-orchestration',
    description: 'Grid-scale battery storage, HVDC transmission networks, and AI dispatch algorithms for 100% clean power.',
    cover_url: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Environment & Ecology',
    author: 'Clean Grid Taskforce',
    publication_date: '2025-08-30',
    page_count: 14,
    file_size: 3670016,
    is_published: true,
    display_order: 8,
  },
  {
    id: '9',
    book_number: 9,
    title: 'Neurobiology & Cognitive Augmented Interfaces',
    slug: 'neurobiology-cognitive-interfaces',
    description: 'Neural decoding, non-invasive BCI bandwidth breakthroughs, and human-computer symbiosis paradigms.',
    cover_url: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Science & Astrophysics',
    author: 'Dr. Sarah Lin',
    publication_date: '2025-07-22',
    page_count: 14,
    file_size: 6291456,
    is_published: true,
    display_order: 9,
  },
  {
    id: '10',
    book_number: 10,
    title: 'Fintech Disruption & Autonomous Financial Systems',
    slug: 'fintech-disruption-systems',
    description: 'Decentralized liquidity protocols, algorithmic settlement, and central bank digital currency frameworks.',
    cover_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Technology & Business',
    author: 'Financial Engineering Review',
    publication_date: '2025-06-11',
    page_count: 14,
    file_size: 3407872,
    is_published: true,
    display_order: 10,
  },
  {
    id: '11',
    book_number: 11,
    title: 'Urban Ecology: Rewilding Metropolitan Centers',
    slug: 'urban-ecology-rewilding',
    description: 'Living walls, urban micro-forests, biodiversity corridors, and water-retaining sponge city infrastructure.',
    cover_url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Architecture & Design',
    author: 'Urban Nature Consortium',
    publication_date: '2025-05-19',
    page_count: 14,
    file_size: 4194304,
    is_published: true,
    display_order: 11,
  },
  {
    id: '12',
    book_number: 12,
    title: 'Photography Annual: Light, Shadows & Silence',
    slug: 'photography-annual-light-shadows',
    description: 'Curated selection of international monochrome landscape photography, darkroom techniques, and fine art prints.',
    cover_url: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Visual Arts',
    author: 'International Guild of Photography',
    publication_date: '2025-04-15',
    page_count: 14,
    file_size: 7340032,
    is_published: true,
    display_order: 12,
  },
  {
    id: '13',
    book_number: 13,
    title: 'Synthetic Biology & Cellular Engineering',
    slug: 'synthetic-biology-cellular-engineering',
    description: 'CRISPR base editing, metabolic pathway design for biomanufacturing, and synthetic cell chassis analysis.',
    cover_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Science & Astrophysics',
    author: 'Biotech Science Press',
    publication_date: '2025-03-28',
    page_count: 14,
    file_size: 5767168,
    is_published: true,
    display_order: 13,
  },
  {
    id: '14',
    book_number: 14,
    title: 'Autonomous Robotics: Perception & Dexterity',
    slug: 'autonomous-robotics-perception',
    description: 'Reinforcement learning for manipulation, multi-modal sensor fusion, and humanoid biomechanics review.',
    cover_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Technology & Business',
    author: 'Robotics Engineering Society',
    publication_date: '2025-02-14',
    page_count: 14,
    file_size: 4980736,
    is_published: true,
    display_order: 14,
  },
  {
    id: '15',
    book_number: 15,
    title: 'The Nordic Architecture Manifesto',
    slug: 'nordic-architecture-manifesto',
    description: 'Light calibration, sustainable mass timber, vernacular warmth, and social connectivity in Scandinavian homes.',
    cover_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Architecture & Design',
    author: 'Nordic Design Council',
    publication_date: '2025-01-20',
    page_count: 14,
    file_size: 3932160,
    is_published: true,
    display_order: 15,
  },
  {
    id: '16',
    book_number: 16,
    title: 'Circular Economy & Closed-Loop Manufacturing',
    slug: 'circular-economy-manufacturing',
    description: 'Zero-waste industrial symbiosis, biomaterials, polymer upcycling, and regenerative product lifecycle design.',
    cover_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Environment & Ecology',
    author: 'Institute for Circular Design',
    publication_date: '2024-12-08',
    page_count: 14,
    file_size: 2883584,
    is_published: true,
    display_order: 16,
  },
  {
    id: '17',
    book_number: 17,
    title: 'Sculptural Forms in Raw Concrete & Steel',
    slug: 'sculptural-forms-concrete-steel',
    description: 'Brutalist heritage, expressive structural engineering, and modern tactile finishes in museum architecture.',
    cover_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Visual Arts',
    author: 'Claire Delacroix',
    publication_date: '2024-11-12',
    page_count: 14,
    file_size: 3407872,
    is_published: true,
    display_order: 17,
  },
  {
    id: '18',
    book_number: 18,
    title: 'Genomics & Precision Oncology Quarterly',
    slug: 'genomics-precision-oncology',
    description: 'Targeted immunotherapy markers, liquid biopsy diagnostics, and single-cell sequencing in clinical trials.',
    cover_url: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Science & Astrophysics',
    author: 'Medical Genetics Review',
    publication_date: '2024-10-25',
    page_count: 14,
    file_size: 5242880,
    is_published: true,
    display_order: 18,
  },
  {
    id: '19',
    book_number: 19,
    title: 'Cybersecurity Threat Intelligence 2026',
    slug: 'cybersecurity-threat-intelligence',
    description: 'Post-quantum encryption readiness, zero-trust perimeter telemetry, and autonomous cyber defense matrices.',
    cover_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Technology & Business',
    author: 'Cyber Defense Alliance',
    publication_date: '2024-09-18',
    page_count: 14,
    file_size: 4456448,
    is_published: true,
    display_order: 19,
  },
  {
    id: '20',
    book_number: 20,
    title: 'Contemporary Ceramic Art: Clay & Fire',
    slug: 'contemporary-ceramic-art',
    description: 'Studio pottery retrospectives, wood-fired kilns, crystalline glazes, and modern organic porcelain works.',
    cover_url: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Visual Arts',
    author: 'Sora Tanaka',
    publication_date: '2024-08-04',
    page_count: 14,
    file_size: 3145728,
    is_published: true,
    display_order: 20,
  },
  {
    id: '21',
    book_number: 21,
    title: 'Agritech & Precision Indoor Farming',
    slug: 'agritech-precision-farming',
    description: 'Vertical hydroponics, spectrum-tailored LED lighting, and computer vision nutrient monitoring for sustainable yield.',
    cover_url: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Environment & Ecology',
    author: 'Agricultural Futures Lab',
    publication_date: '2024-07-16',
    page_count: 14,
    file_size: 3670016,
    is_published: true,
    display_order: 21,
  },
  {
    id: '22',
    book_number: 22,
    title: 'High-Speed Rail & Megacity Logistics',
    slug: 'high-speed-rail-logistics',
    description: 'Maglev feasibility studies, aerodynamic pantograph dampening, and automated intermodal freight hubs.',
    cover_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Architecture & Design',
    author: 'Transportation Research Forum',
    publication_date: '2024-06-22',
    page_count: 14,
    file_size: 4718592,
    is_published: true,
    display_order: 22,
  },
  {
    id: '23',
    book_number: 23,
    title: 'Computational Linguistics & Neural Semantics',
    slug: 'computational-linguistics-semantics',
    description: 'Vector embeddings geometry, multilingual tokenization alignment, and semantic reasoning evaluation.',
    cover_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Technology & Business',
    author: 'Language Intelligence Group',
    publication_date: '2024-05-10',
    page_count: 14,
    file_size: 3932160,
    is_published: true,
    display_order: 23,
  },
  {
    id: '24',
    book_number: 24,
    title: 'High-Altitude Wilderness Expeditions',
    slug: 'high-altitude-expeditions',
    description: 'Alpine mountaineering chronicles, glaciology measurements, and extreme climate endurance gear analysis.',
    cover_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Environment & Ecology',
    author: 'Alpine Exploration Society',
    publication_date: '2024-04-18',
    page_count: 14,
    file_size: 6815744,
    is_published: true,
    display_order: 24,
  },
  {
    id: '25',
    book_number: 25,
    title: 'The Future of Public Libraries in the Digital Era',
    slug: 'future-of-public-libraries',
    description: 'Community knowledge commons, spatial acoustics, archive digitization, and democratic access to digital assets.',
    cover_url: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=800&auto=format&fit=crop',
    pdf_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    category: 'Architecture & Design',
    author: 'Library Sciences Foundation',
    publication_date: '2024-03-30',
    page_count: 14,
    file_size: 3145728,
    is_published: true,
    display_order: 25,
  },
];

// Helper to get local demo books (for instant offline & preview capability)
export function getLocalBooks(): Book[] {
  try {
    const saved = localStorage.getItem(STORAGE_KEYS.ADMIN_DEMO_BOOKS);
    if (saved) {
      return JSON.parse(saved);
    }
  } catch (err) {
    console.warn('Failed to parse demo books from storage:', err);
  }
  return INITIAL_BOOKS;
}

export function saveLocalBooks(books: Book[]): void {
  try {
    localStorage.setItem(STORAGE_KEYS.ADMIN_DEMO_BOOKS, JSON.stringify(books));
  } catch (err) {
    console.warn('Failed to save demo books to storage:', err);
  }
}
